apiVersion: v1
kind: Pod
metadata:
  name: crash-pod-example
  namespace: kubepocket
spec:
  containers:
    - name: crash-container
      image: busybox:latest
      command: ["/bin/sh"]
      args: ["-c", "exit 1"] # Hemen crash olur
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
      resources:
        limits:
          memory: "50Mi"
        requests:
          memory: "25Mi"
