apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
  namespace: kubepocket
spec:
  containers:
    - name: liveness-container
      image: busybox:latest
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo 'Çalışıyor...'; sleep 10; done"]
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/missing-file # ❌ Bu dosya yok, probe başarısız olacak
        initialDelaySeconds: 5
        periodSeconds: 5
