apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
  namespace: kubepocket
spec:
  containers:
    - name: readiness-container
      image: nginx:latest
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /health
          port: 8080 # ❌ Nginx 80'de çalışır, 8080'de değil
        initialDelaySeconds: 5
        periodSeconds: 5
